Repository readmeio/api, pull requests merged in 2022-07, with the labels that each got.

#484 feat: add support for github blob URLs
  packages/api/src/fetcher.ts
  packages/api/test/fetcher.test.ts
Labels: enhancement, area:sdk

#482 feat: improved typescript method accessor `path` type generation
  packages/api/src/cli/codegen/languages/typescript.ts
  packages/api/test/__fixtures__/definitions/operationid-quirks.json
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.d.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.ts
  packages/api/test/__fixtures__/sdk/petstore/index.d.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.d.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/__fixtures__/sdk/simple-ts/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-ts/index.ts
Labels: enhancement, area:sdk

#485 chore: move ESLint/Prettier config to root, format docs
  .alexignore
  .alexrc.js
  .eslintignore
  .eslintrc
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .prettierignore
  docs/authentication.md
  docs/faq.md
  docs/how-it-works.md
  docs/installation.md
  docs/parameters-and-payloads.md
  docs/usage.md
  package-lock.json
  package.json
  packages/api/.eslintignore
  packages/api/.prettierignore
  packages/api/README.md
  packages/api/package-lock.json
  packages/api/package.json
  packages/httpsnippet-client-api/.eslintignore
  packages/httpsnippet-client-api/.prettierignore
  packages/httpsnippet-client-api/README.md
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/package.json
Labels: refactor, documentation

#487 docs(v5): kanad edits
  docs/getting-started.md
  docs/how-it-works.md
  docs/installation.md
  docs/parameters-and-payloads.md
  docs/server-configurations.md
  docs/usage.md
  packages/api/README.md
  packages/api/package.json
Labels: documentation

#490 ci: getting started content reuse using hercule
  .github/workflows/docs.yml
  .gitignore
  bin/build-markdown.js
  docs/getting-started.md
  package-lock.json
  package.json
Labels: enhancement, documentation

#491 feat: updating httpsnippet-client-api to be compatible with httpsnippet v4
  package-lock.json
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.js
  packages/httpsnippet-client-api/test/index.test.js
Labels: enhancement

#494 fix: generated SDKs now ship an IFEE
  .prettierignore
  docs/usage.md
  packages/api/README.md
  packages/api/src/cli/codegen/languages/typescript.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.d.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.ts
  packages/api/test/__fixtures__/sdk/petstore/index.d.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.d.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/__fixtures__/sdk/simple-ts/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-ts/index.ts
  packages/api/test/cli/codegen/languages/typescript.test.ts
Labels: enhancement, refactor, area:sdk

#497 fix: bug where operationIDs with underscores were being modified
  package-lock.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/cache.ts
  packages/api/src/cli/codegen/languages/typescript.ts
  packages/api/src/cli/storage.ts
  packages/api/src/core/getJSONSchemaDefaults.ts
  packages/api/src/core/index.ts
  packages/api/src/core/prepareParams.ts
  packages/api/src/fetcher.ts
  packages/api/src/index.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.d.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/auth.test.ts
  packages/api/test/cache.test.ts
  packages/api/test/cli/storage.test.ts
  packages/api/test/config.test.ts
  packages/api/test/core/prepareAuth.test.ts
  packages/api/test/dist.test.ts
  packages/api/test/index.test.ts
  packages/api/test/integration.test.ts
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/__datasets__/application-form-encoded/index.ts
  packages/httpsnippet-client-api/test/__datasets__/application-json/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-apikey-cookie/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-apikey-header/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-full/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-password-only/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-username-only/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-bearer/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-query/index.ts
  packages/httpsnippet-client-api/test/__datasets__/cookies/index.ts
  packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/index.ts
  packages/httpsnippet-client-api/test/__datasets__/full/index.ts
  packages/httpsnippet-client-api/test/__datasets__/headers/index.ts
  packages/httpsnippet-client-api/test/__datasets__/http-insecure/index.ts
  packages/httpsnippet-client-api/test/__datasets__/issue-128/index.ts
  packages/httpsnippet-client-api/test/__datasets__/issue-76/index.ts
  packages/httpsnippet-client-api/test/__datasets__/issue-78-operationid/index.ts
  packages/httpsnippet-client-api/test/__datasets__/issue-78/index.ts
  packages/httpsnippet-client-api/test/__datasets__/jsonObj-multiline/index.ts
  packages/httpsnippet-client-api/test/__datasets__/jsonObj-null-value/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-data/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-file/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-form-data-no-params/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-form-data/index.ts
  packages/httpsnippet-client-api/test/__datasets__/operationid-non-alphanumerical/index.ts
  packages/httpsnippet-client-api/test/__datasets__/operationid-with-underscores/index.ts
  packages/httpsnippet-client-api/test/__datasets__/operationid-with-underscores/output.js
  packages/httpsnippet-client-api/test/__datasets__/petstore/index.ts
  packages/httpsnippet-client-api/test/__datasets__/query/index.ts
  packages/httpsnippet-client-api/test/__datasets__/short/index.ts
  packages/httpsnippet-client-api/test/__datasets__/text-plain/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: bug, area:sdk

#495 feat: adding support for case-insensitive header parameters
  package-lock.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/core/prepareParams.ts
  packages/api/test/core/prepareParams.test.ts
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/__datasets__/headers/index.ts
  packages/httpsnippet-client-api/test/__datasets__/headers/openapi.json
  packages/httpsnippet-client-api/test/__datasets__/headers/output.js
  packages/httpsnippet-client-api/test/__datasets__/petstore/output.js
Labels: enhancement, area:sdk, area:snippets

#496 fix: removing undefined objects from incoming metadata parameters
  package-lock.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/core/prepareParams.ts
  packages/api/test/core/prepareParams.test.ts
  packages/httpsnippet-client-api/package-lock.json
Labels: bug, area:sdk
