Repository readmeio/api, pull requests merged in 2022-04, with the labels that each got.

#428 feat: decoupling the spec fetching process from the caching library
  packages/api/src/cache.ts
  packages/api/src/fetcher.ts
  packages/api/src/index.ts
  packages/api/src/types.ts
  packages/api/test/auth.test.ts
  packages/api/test/cache.test.ts
  packages/api/test/config.test.ts
  packages/api/test/core/prepareAuth.test.ts
  packages/api/test/dist.test.ts
  packages/api/test/fetcher.test.ts
  packages/api/test/index.test.ts
  packages/api/test/integration.test.ts
Labels: refactor, area:sdk

#429 perf: codegen performance improvements
  package-lock.json
  packages/api/.mocharc.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/codegen/typescript.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/codegen/typescript.test.ts
Labels: performance, refactor, area:sdk

#431 fix(auth): remove the ability to have auth chained with each request
  README.md
  packages/api/README.md
  packages/api/src/core/index.ts
  packages/api/src/core/prepareAuth.ts
  packages/api/src/index.ts
  packages/api/test/auth.test.ts
  packages/api/test/core/prepareAuth.test.ts
Labels: area:sdk
