Repository readmeio/api, pull requests merged in 2023-09, with the labels that each got.

#711 chore(deps): bumping out of date deps
  .github/dependabot.yml
  docs/how-it-works.md
  package-lock.json
  package.json
  packages/api/package.json
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/readme/schemas.ts
  packages/api/test/__fixtures__/sdk/readme/types.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/cache.test.ts
  packages/api/test/cli/storage.test.ts
  packages/api/test/fetcher.test.ts
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-full/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-password-only/index.ts
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-username-only/index.ts
Labels: dependencies

#719 chore(deps): upgrading to typescript 5
  package-lock.json
  packages/api/package.json
  packages/httpsnippet-client-api/package.json
Labels: dependencies

#722 feat: drop support for node 16 and move to require native fetch
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/smoketest.yml
  package-lock.json
  packages/api/package.json
  packages/api/src/.sink.d.ts
  packages/api/src/cache.ts
  packages/api/src/core/index.ts
  packages/api/src/fetcher.ts
  packages/api/test/cli/storage.test.ts
  packages/api/test/core/parseResponse.test.ts
  packages/api/test/datasets/refresh-dataset
  packages/api/test/fetcher.test.ts
  packages/api/test/helpers/fetch-mock.ts
  packages/api/test/integration.test.ts
  packages/api/tsconfig.json
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/test/__datasets__/multipart-data/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-file/index.ts
  packages/httpsnippet-client-api/test/__datasets__/multipart-form-data/index.ts
  packages/httpsnippet-client-api/test/helpers/fetch-mock.ts
  packages/httpsnippet-client-api/test/index.test.ts
  packages/httpsnippet-client-api/test/tsconfig.json
Labels: enhancement

#696 refactor(ts): strict mode
  packages/api/src/cli/codegen/language.ts
  packages/api/src/cli/codegen/languages/typescript.ts
  packages/api/src/cli/fetcher.ts
  packages/api/src/cli/storage.ts
  packages/api/tsconfig.json
  packages/core/src/index.ts
  packages/core/src/lib/getJSONSchemaDefaults.ts
  packages/core/src/lib/prepareAuth.ts
  packages/core/src/lib/prepareParams.ts
  packages/core/tsconfig.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/tsconfig.json
  packages/test-utils/tsconfig.json
Labels: enhancement

#728 refactor(api): cleaning up the api directory now that core is split out
  packages/api/src/bin.ts
  packages/api/src/codegen/index.ts
  packages/api/src/codegen/language.ts
  packages/api/src/codegen/languages/typescript.ts
  packages/api/src/codegen/languages/typescript/util.ts
  packages/api/src/commands/index.ts
  packages/api/src/commands/install.ts
  packages/api/src/fetcher.ts
  packages/api/src/lib/prompt.ts
  packages/api/src/logger.ts
  packages/api/src/storage.ts
  packages/api/test/__fixtures__/oas.json
  packages/api/test/codegen/languages/typescript.test.ts
  packages/api/test/codegen/languages/typescript/smoketest.test.ts
  packages/api/test/codegen/languages/typescript/utils.test.ts
  packages/api/test/fetcher.test.ts
  packages/api/test/storage.test.ts
Labels: refactor

#729 feat: moving node imports over to using the node: prefix
  .eslintrc
  bin/build-markdown.js
  packages/api/.eslintrc
  packages/api/src/codegen/languages/typescript.ts
  packages/api/src/fetcher.ts
  packages/api/src/storage.ts
  packages/api/test/codegen/languages/typescript.test.ts
  packages/api/test/fetcher.test.ts
  packages/api/test/storage.test.ts
  packages/core/.eslintrc
  packages/core/src/index.ts
  packages/core/src/lib/parseResponse.ts
  packages/core/src/lib/prepareParams.ts
  packages/core/test/index.test.ts
  packages/core/test/lib/prepareParams.test.ts
  packages/httpsnippet-client-api/.eslintrc
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: enhancement

#730 ci: knip
  .alexrc.js
  .alexrc.yml
  knip.ts
  package-lock.json
  package.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript.ts
  packages/api/src/codegen/languages/typescript/util.ts
  packages/api/src/storage.ts
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/test/index.test.ts
Labels: refactor

#731 refactor: rename `@api/core` to `api.core`
  lerna.json
  package-lock.json
  package.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript.ts
  packages/api/test/__fixtures__/sdk/alby/index.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/response-title-quirks/index.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/__fixtures__/sdk/simple-ts/index.ts
  packages/core/README.md
  packages/core/package.json
Labels: refactor

#732 fix: try renaming core pkg to `@readme/api-core`
  package-lock.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript.ts
  packages/api/test/__fixtures__/sdk/alby/index.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/response-title-quirks/index.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/__fixtures__/sdk/simple-ts/index.ts
  packages/core/README.md
  packages/core/package.json
Labels: refactor

#742 chore(deps): bump
  package-lock.json
Labels: dependencies

#743 chore(deps): bump `oas` + friends
  package-lock.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/lib/parseResponse.ts
  packages/core/src/lib/prepareAuth.ts
  packages/core/src/lib/prepareParams.ts
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.ts
  packages/test-utils/package.json
Labels: dependencies

#744 chore(deps): npm up
  package-lock.json
Labels: dependencies

#745 chore(deps): bump fetch-har
  package-lock.json
  packages/core/package.json
Labels: dependencies
