Repository readmeio/api, pull requests merged in 2023-01, with the labels that each got.

#602 fix: failing tests
  packages/api/test/__fixtures__/sdk/alby/index.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/index.ts
  packages/api/test/__fixtures__/sdk/petstore/index.ts
  packages/api/test/__fixtures__/sdk/readme/index.ts
  packages/api/test/__fixtures__/sdk/response-title-quirks/index.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/index.js
  packages/api/test/__fixtures__/sdk/simple-js-esm/index.js
  packages/api/test/__fixtures__/sdk/simple-ts/index.ts
  packages/api/test/cli/codegen/languages/typescript.test.ts
  packages/api/test/helpers/chai-plugins.ts
  packages/api/test/integration.test.ts
Labels: bug

#603 chore: bumping out of date deps
  package-lock.json
  package.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/test/__fixtures__/sdk/alby/types.ts
  packages/api/test/__fixtures__/sdk/petstore/types.ts
  packages/api/test/__fixtures__/sdk/readme/types.ts
  packages/api/test/__fixtures__/sdk/response-title-quirks/types.ts
  packages/api/test/__fixtures__/sdk/simple-js-cjs/types.d.ts
  packages/api/test/__fixtures__/sdk/simple-js-esm/types.d.ts
  packages/api/test/__fixtures__/sdk/simple-ts/types.ts
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/package.json
Labels: bug, dependencies

#606 Adds ESM usage instructions
  docs/usage.md
  packages/api/README.md
Labels: area:sdk, documentation

#607 chore: bumping deps
  package-lock.json
  package.json
  packages/api/package-lock.json
  packages/api/package.json
  packages/api/src/index.ts
  packages/api/test/.eslintrc
  packages/api/test/datasets/real-world-apis.json
  packages/httpsnippet-client-api/package-lock.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/.eslintrc
Labels: dependencies

#605 fix: moving off `fs/promises` to `fs` in client-side code
  packages/api/.eslintrc
  packages/api/src/core/prepareParams.ts
Labels: bug, area:sdk
