Repository readmeio/api, pull requests merged in 2023-10, with the labels that each got.

#746 refactor: remove `make-dir` as a dep
  package-lock.json
  packages/api/package.json
  packages/api/src/storage.ts
Labels: refactor

#753 fix(api): storage dir not being set properly
  packages/api/src/storage.ts
  packages/api/test/storage.test.ts
Labels: bug, area:sdk

#755 refactor(api): minor refactors to how some internal language classes are used
  packages/api/src/codegen/codegenerator.ts
  packages/api/src/codegen/factory.ts
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/commands/install.ts
  packages/api/test/codegen/languages/typescript/index.test.ts
  packages/api/test/codegen/languages/typescript/smoketest.test.ts
Labels: refactor, area:sdk

#759 fix: minor `tsup` codegen fixes
  package-lock.json
  packages/api/bin/api.js
  packages/api/package.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/tsconfig.json
Labels: bug, refactor

#760 refactor(core): removing `oas` as a dependency on codegen'd SDKs
  package-lock.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/test/__fixtures__/sdk/alby/package.json
  packages/api/test/__fixtures__/sdk/alby/src/index.ts
  packages/api/test/__fixtures__/sdk/operationid-quirks/package.json
  packages/api/test/__fixtures__/sdk/operationid-quirks/src/index.ts
  packages/api/test/__fixtures__/sdk/optional-payload/package.json
  packages/api/test/__fixtures__/sdk/optional-payload/src/index.ts
  packages/api/test/__fixtures__/sdk/petstore/package.json
  packages/api/test/__fixtures__/sdk/petstore/src/index.ts
  packages/api/test/__fixtures__/sdk/readme/package.json
  packages/api/test/__fixtures__/sdk/readme/src/index.ts
  packages/api/test/__fixtures__/sdk/response-title-quirks/package.json
  packages/api/test/__fixtures__/sdk/response-title-quirks/src/index.ts
  packages/api/test/__fixtures__/sdk/simple/package.json
  packages/api/test/__fixtures__/sdk/simple/src/index.ts
  packages/core/src/index.ts
  packages/core/test/index.test.ts
Labels: enhancement, refactor, area:sdk

#761 feat(codegen): required devDeps are now listed in `package.json`
  packages/api/src/codegen/codegenerator.ts
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/commands/install.ts
  packages/api/test/__fixtures__/sdk/alby/package.json
  packages/api/test/__fixtures__/sdk/operationid-quirks/package.json
  packages/api/test/__fixtures__/sdk/optional-payload/package.json
  packages/api/test/__fixtures__/sdk/petstore/package.json
  packages/api/test/__fixtures__/sdk/readme/package.json
  packages/api/test/__fixtures__/sdk/response-title-quirks/package.json
  packages/api/test/__fixtures__/sdk/simple/package.json
Labels: enhancement, area:sdk

#764 feat(core): moving `json-schema-to-ts` directly into the `core` package
  package-lock.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/core/package.json
  packages/core/src/lib/index.ts
  packages/core/tsup.config.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/alby/src/types.ts
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/metrotransit/src/types.ts
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/optional-payload/src/types.ts
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/petstore/src/types.ts
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/readme/src/types.ts
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/response-title-quirks/src/types.ts
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/simple/src/types.ts
  packages/test-utils/sdks/star-trek/package.json
  packages/test-utils/sdks/star-trek/src/types.ts
Labels: enhancement, area:sdk

#765 chore(deps): bumping all out of date dependencies
  .eslintrc
  .github/dependabot.yml
  package-lock.json
  package.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/test/codegen/languages/typescript/index.test.ts
  packages/core/package.json
  packages/core/src/lib/prepareParams.ts
  packages/core/tsup.config.ts
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/tsup.config.ts
  packages/test-utils/package.json
Labels: dependencies

#763 feat(cli): prompting the user to use `info.title` for their installed SDK
  package-lock.json
  packages/api/package.json
  packages/api/src/commands/install.ts
  packages/api/src/storage.ts
Labels: enhancement, area:cli

#767 feat(httpsnippet-client-api): updates for v7 compatibility + custom variable support
  packages/api/src/fetcher.ts
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/__datasets__/alternate-server/output.js
  packages/httpsnippet-client-api/test/__datasets__/application-form-encoded/output.js
  packages/httpsnippet-client-api/test/__datasets__/application-json/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-apikey-cookie/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-apikey-header/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-full/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-password-only/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-basic-username-only/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-bearer/output.js
  packages/httpsnippet-client-api/test/__datasets__/auth-query/output.js
  packages/httpsnippet-client-api/test/__datasets__/cookies/output.js
  packages/httpsnippet-client-api/test/__datasets__/full-many-query-params/output.js
  packages/httpsnippet-client-api/test/__datasets__/full/output.js
  packages/httpsnippet-client-api/test/__datasets__/headers/output.js
  packages/httpsnippet-client-api/test/__datasets__/http-insecure/output.js
  packages/httpsnippet-client-api/test/__datasets__/issue-128/output.js
  packages/httpsnippet-client-api/test/__datasets__/issue-76/output.js
  packages/httpsnippet-client-api/test/__datasets__/issue-78-operationid/output.js
  packages/httpsnippet-client-api/test/__datasets__/issue-78/output.js
  packages/httpsnippet-client-api/test/__datasets__/jsonObj-multiline/output.js
  packages/httpsnippet-client-api/test/__datasets__/jsonObj-null-value/output.js
  packages/httpsnippet-client-api/test/__datasets__/multipart-data/output.js
  packages/httpsnippet-client-api/test/__datasets__/multipart-file/output.js
  packages/httpsnippet-client-api/test/__datasets__/multipart-form-data-no-params/output.js
  packages/httpsnippet-client-api/test/__datasets__/multipart-form-data/output.js
  packages/httpsnippet-client-api/test/__datasets__/operationid-non-alphanumerical/output.js
  packages/httpsnippet-client-api/test/__datasets__/operationid-with-underscores/output.js
  packages/httpsnippet-client-api/test/__datasets__/parameter-special-characters/output.js
  packages/httpsnippet-client-api/test/__datasets__/petstore/output.js
  packages/httpsnippet-client-api/test/__datasets__/query/output.js
  packages/httpsnippet-client-api/test/__datasets__/short/output.js
  packages/httpsnippet-client-api/test/__datasets__/text-plain/output.js
  packages/httpsnippet-client-api/test/index.test.ts
Labels: enhancement, area:snippets

#768 fix(httpsnippet-client-api): retain casing for non-reserved headers
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/__datasets__/headers/index.ts
  packages/httpsnippet-client-api/test/__datasets__/headers/openapi.json
  packages/httpsnippet-client-api/test/__datasets__/headers/output.js
Labels: bug, area:snippets

#771 feat(api): exposing `openapi.json` to codegen'd `package.json` files
  packages/api/src/codegen/languages/typescript/index.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/star-trek/package.json
Labels: enhancement, area:sdk

#770 fix(cjs): include get-stream directly in bundle
  package-lock.json
  packages/core/package.json
  packages/core/src/lib/prepareParams.ts
  packages/core/tsup.config.ts
Labels: bug, area:sdk

#773 feat(api): adding a `$schema` property to generated `api.json` lockfiles
  .gitignore
  package-lock.json
  packages/api/package.json
  packages/api/schema.json
  packages/api/src/storage.ts
  packages/api/test/storage.test.ts
Labels: enhancement, area:sdk

#775 feat(api): creation of a new `list` command
  package-lock.json
  packages/api/package.json
  packages/api/schema.json
  packages/api/src/commands/index.ts
  packages/api/src/commands/list.ts
  packages/api/src/storage.ts
  packages/api/test/storage.test.ts
Labels: enhancement, area:cli

#778 ci: cleanup
  .github/workflows/ci.yml
  packages/api/package.json
Labels: refactor

#774 feat: add a placeholder `README` file in codegen'd directory
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/test/codegen/languages/typescript/index.test.ts
  packages/test-utils/sdks/alby/README.md
  packages/test-utils/sdks/metrotransit/README.md
  packages/test-utils/sdks/operationid-quirks/README.md
  packages/test-utils/sdks/optional-payload/README.md
  packages/test-utils/sdks/petstore/README.md
  packages/test-utils/sdks/readme/README.md
  packages/test-utils/sdks/response-title-quirks/README.md
  packages/test-utils/sdks/simple/README.md
  packages/test-utils/sdks/star-trek/README.md
Labels: enhancement, area:sdk

#776 feat(api): addition of a new uninstall command
  docs/how-it-works.md
  packages/api/schema.json
  packages/api/src/codegen/codegenerator.ts
  packages/api/src/codegen/factory.ts
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/commands/index.ts
  packages/api/src/commands/install.ts
  packages/api/src/commands/list.ts
  packages/api/src/commands/uninstall.ts
  packages/api/src/storage.ts
  packages/api/test/codegen/languages/typescript/index.test.ts
  packages/api/test/storage.test.ts
Labels: enhancement, area:cli

#777 refactor(lockfile): consolidate TS and JSON schema type definitions
  packages/api/bin/buildVersionedFiles.ts
  packages/api/package.json
  packages/api/schema.json
  packages/api/src/codegen/factory.ts
  packages/api/src/commands/install.ts
  packages/api/src/lockfileSchema.ts
  packages/api/src/storage.ts
Labels: enhancement, refactor

#779 fix: add caret to package.json dep
  packages/api/src/codegen/languages/typescript/index.ts
Labels: bug, area:sdk

#781 fix(core): funky type issues with the main export exporting multiple things
  packages/api/src/codegen/languages/typescript/index.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/types.ts
  packages/core/tsup.config.ts
  packages/test-utils/sdks/alby/src/index.ts
  packages/test-utils/sdks/metrotransit/src/index.ts
  packages/test-utils/sdks/operationid-quirks/src/index.ts
  packages/test-utils/sdks/optional-payload/src/index.ts
  packages/test-utils/sdks/petstore/src/index.ts
  packages/test-utils/sdks/readme/src/index.ts
  packages/test-utils/sdks/response-title-quirks/src/index.ts
  packages/test-utils/sdks/simple/src/index.ts
  packages/test-utils/sdks/star-trek/src/index.ts
Labels: bug, area:sdk

#783 feat(api): improvements to the installation screen
  package-lock.json
  packages/api/package.json
  packages/api/src/commands/install.ts
  packages/api/src/lib/suggestedOperations.ts
  packages/api/test/lib/__snapshots__/suggestedOperations.test.ts.snap
  packages/api/test/lib/suggestedOperations.test.ts
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: enhancement, area:cli

#785 refactor(api): refactor core to handle HAR generation for code snippets
  package-lock.json
  packages/api/package.json
  packages/api/src/lib/suggestedOperations.ts
  packages/core/src/index.ts
  packages/core/src/lib/prepareAuth.ts
Labels: refactor, area:cli

#786 feat(api): creating LICENSE files and and SDK headings
  package-lock.json
  packages/api/.eslintrc
  packages/api/package.json
  packages/api/src/codegen/codegenerator.ts
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/storage.ts
  packages/api/test/codegen/languages/typescript/index.test.ts
  packages/api/test/fetcher.test.ts
  packages/api/test/storage.test.ts
  packages/test-utils/definitions/simple.json
  packages/test-utils/sdks/alby/README.md
  packages/test-utils/sdks/alby/src/index.ts
  packages/test-utils/sdks/metrotransit/README.md
  packages/test-utils/sdks/metrotransit/src/index.ts
  packages/test-utils/sdks/operationid-quirks/README.md
  packages/test-utils/sdks/operationid-quirks/src/index.ts
  packages/test-utils/sdks/optional-payload/README.md
  packages/test-utils/sdks/optional-payload/src/index.ts
  packages/test-utils/sdks/petstore/LICENSE
  packages/test-utils/sdks/petstore/README.md
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/petstore/src/index.ts
  packages/test-utils/sdks/readme/README.md
  packages/test-utils/sdks/readme/src/index.ts
  packages/test-utils/sdks/response-title-quirks/README.md
  packages/test-utils/sdks/response-title-quirks/src/index.ts
  packages/test-utils/sdks/simple/README.md
  packages/test-utils/sdks/simple/src/index.ts
  packages/test-utils/sdks/star-trek/README.md
  packages/test-utils/sdks/star-trek/src/index.ts
Labels: enhancement, area:sdk

#782 feat: tsconfig, gitignore, npm script enhancements
  packages/api/src/codegen/languages/typescript/index.ts
  packages/test-utils/sdks/alby/.gitignore
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/alby/tsconfig.json
  packages/test-utils/sdks/metrotransit/.gitignore
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/metrotransit/tsconfig.json
  packages/test-utils/sdks/operationid-quirks/.gitignore
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/operationid-quirks/tsconfig.json
  packages/test-utils/sdks/optional-payload/.gitignore
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/optional-payload/tsconfig.json
  packages/test-utils/sdks/petstore/.gitignore
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/petstore/tsconfig.json
  packages/test-utils/sdks/readme/.gitignore
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/readme/tsconfig.json
  packages/test-utils/sdks/response-title-quirks/.gitignore
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/response-title-quirks/tsconfig.json
  packages/test-utils/sdks/simple/.gitignore
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/simple/tsconfig.json
  packages/test-utils/sdks/star-trek/.gitignore
  packages/test-utils/sdks/star-trek/package.json
  packages/test-utils/sdks/star-trek/tsconfig.json
Labels: enhancement, area:sdk

#787 fix(core): refactoring `FromSchema` out of core
  package-lock.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/lockfileSchema.ts
  packages/core/package.json
  packages/core/src/lib/index.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/alby/src/types.ts
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/metrotransit/src/types.ts
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/optional-payload/src/types.ts
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/petstore/src/types.ts
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/readme/src/types.ts
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/response-title-quirks/src/types.ts
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/simple/src/types.ts
  packages/test-utils/sdks/star-trek/package.json
  packages/test-utils/sdks/star-trek/src/types.ts
Labels: bug, area:sdk

#792 refactor(snippets): moving the library over to be an HTTPSnippet plugin
  package-lock.json
  packages/api/src/lib/suggestedOperations.ts
  packages/httpsnippet-client-api/README.md
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: enhancement, refactor, area:snippets

#793 fix(api): run `npm install` with `--ignore-scripts`
  packages/api/src/codegen/languages/typescript/index.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/star-trek/package.json
Labels: bug, area:cli

#795 feat: syntax highlighting on example snippet
  package-lock.json
  packages/api/package.json
  packages/api/src/commands/install.ts
Labels: enhancement, area:cli

#796 feat(codegen): expose `package.json` in `exports` object
  packages/api/src/codegen/languages/typescript/index.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/star-trek/package.json
Labels: enhancement, area:core

#794 feat: throw error for legacy dynamic `require` users
  packages/api/.gitignore
  packages/api/legacy-require-handler.cjs
  packages/api/package.json
Labels: enhancement, area:core

#797 chore(deps): upgrading all of our oas deps to their latest releases
  package-lock.json
  packages/api/package.json
  packages/core/package.json
  packages/httpsnippet-client-api/package.json
  packages/test-utils/package.json
Labels: dependencies

#801 feat(core): bring `FromSchema` back into core
  package-lock.json
  packages/api/package.json
  packages/api/src/codegen/languages/typescript/index.ts
  packages/api/src/lockfileSchema.ts
  packages/core/package.json
  packages/core/src/types.ts
  packages/test-utils/sdks/alby/package.json
  packages/test-utils/sdks/alby/src/types.ts
  packages/test-utils/sdks/metrotransit/package.json
  packages/test-utils/sdks/metrotransit/src/types.ts
  packages/test-utils/sdks/operationid-quirks/package.json
  packages/test-utils/sdks/optional-payload/package.json
  packages/test-utils/sdks/optional-payload/src/types.ts
  packages/test-utils/sdks/petstore/package.json
  packages/test-utils/sdks/petstore/src/types.ts
  packages/test-utils/sdks/readme/package.json
  packages/test-utils/sdks/readme/src/types.ts
  packages/test-utils/sdks/response-title-quirks/package.json
  packages/test-utils/sdks/response-title-quirks/src/types.ts
  packages/test-utils/sdks/simple/package.json
  packages/test-utils/sdks/simple/src/types.ts
  packages/test-utils/sdks/star-trek/package.json
  packages/test-utils/sdks/star-trek/src/types.ts
Labels: enhancement, area:core, area:api
