Repository readmeio/api, pull requests merged in 2024-04, with the labels that each got.

#873 fix: swap out `ts-node` for `tsimp`
  .prettierignore
  package-lock.json
  packages/api/.gitignore
  packages/api/package.json
Labels: bug, refactor

#874 chore: bump deps, fix types
  package-lock.json
  package.json
  packages/api/package.json
  packages/core/package.json
  packages/httpsnippet-client-api/package.json
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: bug, dependencies

#875 fix: zsh compatibility for `api` installation instructions
  packages/httpsnippet-client-api/src/index.ts
  packages/httpsnippet-client-api/test/index.test.ts
Labels: bug, area:snippets
